
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SalesManagement.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Order_Details
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Order_Details()
    {

        this.Orders = new HashSet<Order>();

    }


    public System.Guid Id { get; set; }

    public string CustomerFirstName { get; set; }

    public string CustomerLastName { get; set; }

    public int AccountType { get; set; }

    public string DeliveryAddress { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Order> Orders { get; set; }

}

}
