
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SalesManagement.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Sale
{

    public int Id { get; set; }

    public Nullable<int> OrdersId { get; set; }

    public Nullable<int> InventoryId { get; set; }

    public int BudgetId { get; set; }

    public Nullable<int> UserId { get; set; }



    public virtual Budget Budget { get; set; }

    public virtual Order Order { get; set; }

    public virtual User User { get; set; }

}

}
